### PR TITLE
SBTK-199: Change listen group to vhost group

### PR DESCRIPTION
**Pull request by syphernl**

### CODE REVIEW

**Comment by syphernl** [comment]
Not sure why this check is failing, since it doesn't do anything with the file I changed. I guess we can safely merge this, thoughts @eXistenZNL @nstapelbroek ?

**Review by nstapelbroek — CHANGES_REQUESTED** [review]
Since it's Jinja, what about building a fallback to `listen` if `listen_owner` and `listen_group` are undefined. You can then let `listen` fallback to nginx for maximum BC!

**Comment by syphernl** [comment]
@nstapelbroek Technically the template isn't being used by the formula itself but called from the vhosting-formula. However, its probably a good idea to add a default value for that as well. Has now been added.

**Review by nstapelbroek — APPROVED** [review]
Want me to test it before merging? else I'm a fan :+1:

**Comment by syphernl** [comment]
Standalone nothing can be tested. It has to be tested with the vhosting-formula. 
You may do that, or merge it and (optionally) test it when I have created a PR for that.

**Pull request merged**
